# Generated by Django 5.0 on 2025-11-15 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20),
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_calories', models.PositiveIntegerField()),
                ('target_protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_carbs_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'user_type': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_nutrition_plans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'normal'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_plans',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='nutrition_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_meals', to='nutrition.nutritionplan'),
        ),
        migrations.CreateModel(
            name='NutritionPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20)),
                ('scheduled_time', models.TimeField(help_text='Recommended time to consume this meal')),
                ('target_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('target_protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_pre_workout', models.BooleanField(default=False, help_text='Meal should be consumed before training')),
                ('is_post_workout', models.BooleanField(default=False, help_text='Meal should be consumed after training')),
                ('notes', models.TextField(blank=True, help_text='Guidance on meal timing and composition', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of meal within the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionplan')),
            ],
            options={
                'db_table': 'nutrition_plan_meals',
                'ordering': ['scheduled_time', 'order', 'id'],
                'unique_together': {('plan', 'meal_type', 'scheduled_time')},
            },
        ),
    ]
